apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-frontend
  labels:
    app: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
        tier: frontend
    spec:
      containers:
      - name: uwsgi
        image: saramune/flask-app-uwsgi:0.1
        imagePullPolicy: Always
        ports:
        - name: uwsgi
          containerPort: 3031
      - name: nginx
        image: saramune/flask-app-nginx:0.1
        imagePullPolicy: Always
        ports:
        - name: nginx
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-frontend
  labels:
    app: flask-app
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 80
  selector:
    app: flask-app
    tier: frontend
  sessionAffinity: ClientIP